spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_project
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
server:
  port: 8080

